package com.akshpro.distributor.management.system.Controllers;

import com.akshpro.distributor.management.system.InformationPojo.OrderInfo;
import com.akshpro.distributor.management.system.Services.OrderService;
import com.akshpro.distributor.management.system.dto.OrderRequest;
import com.akshpro.distributor.management.system.dto.OrderResponse;
import com.akshpro.distributor.management.system.dto.ProductSalesResponse;
import org.springframework.http.ResponseEntity;
import org.springframework.web.bind.annotation.*;

import java.util.List;


@RestController
@RequestMapping("/orders")
public class OrderController {


    private final OrderService orderService;


    public OrderController(OrderService orderService, OrderService orderService1) {
        this.orderService = orderService1;
    }

    //================ ========================================================


    // Add order
    @PostMapping("/create")
    public ResponseEntity<?> createOrder(@RequestBody OrderRequest request) {

        return ResponseEntity.ok(
                orderService.createOrder(
                        request.getDealerName(),
                        request.getProductName(),
                        request.getQuantity(),
                        request.getOrderDate()
                )
        );
    }


    // view All Orders
    @GetMapping("/view")
    public ResponseEntity<List<OrderInfo>> vieworder() {
        List<OrderInfo> allOrders = orderService.viewAllOrders();
        return ResponseEntity.ok(allOrders);
    }


    // All orders of Perticular User(by Id)
    @GetMapping("/dealer/{id}")
    public ResponseEntity<List<OrderResponse>> getOrdersByDealer(@PathVariable long id) {

        return ResponseEntity.ok(orderService.getOrdersByDealer(id));
    }


    // delete order by id
    @DeleteMapping("/{id}")
    public ResponseEntity<?> deleteOrder(@PathVariable long id) {
        boolean deleteOrNot = orderService.deleteorder(id);
        if (deleteOrNot) {
            return ResponseEntity.ok().build();
        }

        return ResponseEntity.notFound().build();
    }


    //get revenue of all business
    @GetMapping("/totalrevenue")
    public ResponseEntity<Double> getRevenue(){
        return ResponseEntity.ok(orderService.getTotalRevenue());
    }





    //get order by product name
    @GetMapping("/product/name/{name}")
    public ResponseEntity<List<OrderResponse>> getOrdersByProductName(@PathVariable String name) {
        return ResponseEntity.ok(orderService.getOrdersByProductName(name));
    }


    // get orders by product id
    @GetMapping("product/id/{productid}")
    public ResponseEntity<List<OrderResponse>> getOrdersByProductId(@PathVariable long productid) {
        return ResponseEntity.ok(orderService.getOrdersByProductId(productid));
    }


    


    // see recent selling product
    @GetMapping("/recent")
    public ResponseEntity<List<OrderResponse>> getRecentOrders(){
        return ResponseEntity.ok(orderService.getRecentOrders());
    }


    // how many selling of one product, and how many revenue generated by one product
    @GetMapping("/product-sales")
    public ResponseEntity<List<ProductSalesResponse>> getProductSales(){
        return ResponseEntity.ok(orderService.getProductSales());
    }


}

